[project]
name = "accidentalriskanalysis"
version = "0.1.0"
description = "Programming for data science project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "folium>=0.20.0",
    "geopandas>=1.1.1",
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.6",
]
